# Generated by Django 3.2 on 2021-05-17 05:46

# create this file by running the command
#   python manage.py makemigrations --empty --name student student
# In short, the create_data method recovers 
#   the Student model object and creates 
#   initial data, just so that our database 
#   isn’t empty when the API starts.
from django.db import migrations

def create_data(apps, scheme_editor):
    Student = apps.get_model('student', 'Student')
    Student(name="Syed Hussain", email='syed@gmail.com', document='3457853', phone=49574753984).save()

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
